In [4]:
# Memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku = load_iris()

In [6]:
# simpan data fitur/kolom (x) dan target (y)
X = iris_ku.data
Y = iris_ku.target

In [7]:
# simpan nama fitur/kolom (x) dan target (y)
feature_names = iris_ku.feature_names
target_names = iris_ku.target_names

In [8]:
# tampil nama fitur dan target dataset
print ("feature names :", feature_names)
print ("Target names :", target_names)

feature names : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names : ['setosa' 'versicolor' 'virginica']


In [10]:
# x dan y adalah numpy arrays
print("\nType of X is:", type(X))


Type of X is: <class 'numpy.ndarray'>


In [11]:
# tampilkan 5 baris pertama
print("\nFirst 5 rows of X:\n", X[:5])


First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [12]:
# fitur(x) and target(y)
X = iris_ku.data
Y = iris_ku.target

In [13]:
#splitting x dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split
X_latih, X_tes, Y_latih, Y_test = train_test_split(X, Y, test_size=0.4, random_state=1)

In [14]:
#tampilkan data fitur latih dan uji
print(X_latih.shape)
print(X_tes.shape)

(90, 4)
(60, 4)


In [15]:
#pelatihan pada data latih menggunakan KNN (k=3)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_latih, Y_latih)

KNeighborsClassifier(n_neighbors=3)

In [16]:
#melakukan prediksi pada data uji
y_prediksi = knn.predict(X_tes)

In [21]:
#Perbandingan nilai aktual (y_tes) dengan nilai prediksi (y_prediksi)
from sklearn import metrics
print("Akurasi model KNN :", metrics.accuracy_score(Y_test, y_prediksi))

Akurasi model KNN : 0.9833333333333333


In [23]:
contoh = [[3, 5, 4, 2], [2, 3, 5, 4]]
preds = knn.predict(contoh)
pred_species = [iris_ku.target_names[p] for p in preds]
print("Prediksi :", pred_species)

Prediksi : ['versicolor', 'virginica']


In [28]:
#Saving the model
import sklearn.externals
import joblib
joblib.dump(knn, "iris_knn.pkl")

['iris_knn.pkl']